### ISSUE TITLE
Trivial euclidean manifold E(n) ? (feature request)

### ISSUE THREAD

**Issue by markusgft** [artivis/manif#108]
Dear all,

I'm an application which takes an "manif" manifold as a template parameter. This works nicely, since the basic interface, accessors and methods are naturally the same for all manifolds.

However, it fails as soon as I want to operate in Euclidean space. What is missing, is essentially a manif-implementation of the must fundamental n-dimensional Euclidean manifold E(n), in which case anything within manif should fall back to the natural Eigen-types and methods.

Is there any plan to add such a feature?

Best, and thanks in advance!

**Comment by joansola** [comment]
Hi Markus,

We've been discussing for a while the topics you are raising. For the R^n manifolds, or E(n), they should be easy to implement since they are mostly trivial.

We'll discuss soon about this possibility. We'll keep you posted here.

**Comment by markusgft** [comment]
Hi @joansola , thanks for your quick reply! 
I really appreciate "manif" and would highly welcome the extended functionalities!
All the best!

**Comment by artivis** [comment]
@markusgft thanks for your interest in manif!
Implementing the E(n) manifolds has been on my todo-list for a while now but I did not have a use for it outside of the infamous composite manifolds (#84). Given your interest in those I will start looking at the implementation asap.
Best.

**Comment by markusgft** [comment]
Dear @artivis, thanks a lot for taking the action, I'm looking forward to the feature.
