### ISSUE TITLE
What does 'Dim' mean?

### ISSUE THREAD

**Issue by minrui-hust** [artivis/manif#117]
In struct traits<SO2<_Scalar>> in `SO2.h`
```c++
...
using Vector  = Eigen::Matrix<Scalar, DoF, 1>;
```
Should the 'DoF' be 'Dim'?
The DoF of SO2 is 1, but the dimension of the Vector SO2 act on is 2.

**Comment by artivis** [comment]
Hi @minrui-hust,
you actually spotted an error, it should be `using Vector  = Eigen::Matrix<Scalar, Dim, 1>;`. The same error is repeated in all implemented groups. Unfortunately this typedef is not used anywhere hence the mistake was not caught earlier. 
I'll fix this real soon, thanks for the ticket :+1:
