### ISSUE TITLE
.isApprox() with default tolerance for Tangent-types?

### ISSUE THREAD

**Issue by markusgft** [artivis/manif#123]
Just out of curiousity: is there a reason why the method .isApprox() in the Tangent Base class does not have a default value for the tolerance?

If not, would it be an option to add a reasonable default tolerance?

**Comment by artivis** [comment]
There you go #124.

Not sure what you call reasonable but I used the same tolerance as in [`LieGroupBase::isApprox`](https://github.com/artivis/manif/blob/devel/include/manif/impl/lie_group_base.h#L234).
