### ISSUE TITLE
What does the "origin" mean?

### ISSUE THREAD

**Issue by niebayes** [artivis/manif#135]
![image](https://user-images.githubusercontent.com/25320945/84368767-9489dc00-ac08-11ea-8cf6-0195997c1f9f.png)

I can grasp the basic idea of this passage. But the term "origin" confused me. It is the "origin" of the manifold, or that of the tangent vector space? And what is the "origin" of a manifold? 

![image](https://user-images.githubusercontent.com/25320945/84369804-fa2a9800-ac09-11ea-862f-8a99e488ff2f.png)

There's also an "origin" exists in the latter passage, which I assumed to mean "the time instant t = 0". Am I right?

**Comment by joansola** [comment]
Origin has the sense of Identity of the group.
