### ISSUE TITLE
Include operator()(int idx) for manif tangent-types?

### ISSUE THREAD

**Issue by markusgft** [artivis/manif#143]
Dear all, 
I would like to ask whether you would consider it meaningful to introduce the following operator for manif tangent-types, in order to allow direct access to single elements of the coefficient vector of the tangent objects.
I would suggest something along the lines of [this](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4.html#ae6ba07bad9e3026afe54806fdefe32bb)
A trivial way to implement the const-version would be to include the following into `tangent_base.h`
```
Scalar operator()(int idx) const {return coeffs()(idx);}
```

**Comment by artivis** [comment]
I'm introducing the `operator[](i)` in #237. Maybe this can closes the ticket?

**Comment by markusgft** [comment]
Fantastic, please close! Thanks.
