### ISSUE TITLE
chain rules for jacobian of RQR^{-1} wrt R?

### ISSUE THREAD

**Issue by narutojxl** [artivis/manif#145]
Hi, @joansola:
Thanks for your very detailed paper first !
How to calculate the jacobian of $(RQR^{-1})$ wrt R, where R and Q are all SO(3), Q is independent  from R. Thanks for your help :)

**Comment by joansola** [comment]
Hi @narutojxl , thanks!

Interesting question. I do not know. But expressions like RQR\inv are interesting because they have nice properties.

For example, let Q = exp(q^) for q^\in so3

Then RQR.inv = E exp(q) R.inv = exp (R q^ R.inv) = exp (Adj_R(q^)) = Exp (Adj * q) <-- maybe I'm slightly wrong by some small detail, please check the paper for exactness here.

maybe from here you can use the chain rule!

Let me know if you get somewhere safe with this.

**Comment by artivis** [comment]
Some pseudo-code below,

```cpp
SO3d R, Q;
// some initialization
SO3d::Jacobian J_RQ_R, J_RQ_Q, J_Ri_R, J_P_RQ, J_P_Ri, J_P_R, J_P_Q;

SO3d P = R.compose(Q, J_RQ_R, J_RQ_Q).compose(R.inverse(J_Ri_R), J_P_RQ, J_P_Ri);

J_P_R = J_P_RQ * J_RQ_R + J_P_Ri * J_Ri_R; // This is what you want
J_P_Q = J_P_RQ * J_RQ_Q;
```
@joansola can you double-check `J_P_R` chain?

**Comment by joansola** [comment]
@artivis  Since `R*Q*R.inv` is a quadratic form in `R`, I am not sure if we can apply the chain rule blindly, that's why I tried to re-write the expression through manipulations as in my post above.

A nice check then is to compare with `manif` if both approaches match.

**Comment by joansola** [comment]
Nice code, anyway! and the chain looks good to me.

**Comment by joansola** [comment]
1. Method of the manipulation (.i: inverse; q = Log(Q))
```
J^(R*Q*R.i)_R = J^Exp(R*q)_R 
             = J^Exp(R*q)_(R*q) * J^(R*q)_R 
             = Jr(R*q) * (-R*[q]_x) 
             = - Jr(R*q) * R * [q]_x 
```

2. Plain chain rule (.i: inverse ; .tr: transpose)
```
J^(R*Q*R.i)_R = J^(R*Q*R.i)_(R*Q)*J^(R*Q)_R + J^(R*Q*R.i)_R.i*J^R.i_R 
             = R.i.tr * Q.tr + I * (-R)
             = (Q*R.i).tr - R
```

They do not seem to match at all! Maybe manif thinks otherwise?

**Comment by narutojxl** [comment]
Hi @joansola  and @artivis , thanks for your help. I also have the same doubt. 

 
![2020-06-19 05:58:49屏幕截图](https://user-images.githubusercontent.com/6205343/85076300-70bf2b00-b1f2-11ea-85ca-f72f995e75ee.png)

**Comment by joansola** [comment]
In SO3 you cannot assume that `Log(AB) = Log(A)+Log(B)`. If this were true, then:

    Log(AB) = Log(A)+Log(B) = Log(B)+Log(A) = Log(BA) ==> AB = BA 

which is untrue for non-commutative groups.

You have the (I believe) correct development of the Jacobian in case 1. above. You apply the chain rule, not the definition of the derivative, and get there quickly enough.

Method 2 is I believe incorrect.

**Comment by narutojxl** [comment]
Yes, i agree with you :) , thanks all of you !  My problem is solved(i think), i will close the issue.
