### ISSUE TITLE
Avoid to set target_compile_options when compile is gcc

### ISSUE THREAD

**Issue by GiulioRomualdi** [artivis/manif#156]
I'm trying to import `manif` in my application, however when I tried to compile it I got the following errors due to unused-variable. e.g. 
```
error: unused variable ‘contactName’ [-Werror=unused-variable
```

Digging in the code, I realized that it is due to the following lines the main CMakeList.txt file of `manif`
https://github.com/artivis/manif/blob/78cc83d8292736b26a3a4f6d302057a6b80056a4/CMakeLists.txt#L87-L94

Indeed when a library is linked using
```cmake
target_link_libraries(my_library PRIVATE MANIF::manif)
```
the `target_compile_options` defined in `manif` are propagated to `my_library`.

It would be really nice if those options are removed from the interface, indeed it would simplify a lot the usage of `manif` with other libraries. 

The problem can be easily solved with the following patch. Where the `compile options` are removed from the interface and they are added to the `manif_add_gtest` cmake function. Consequentially the tests are still compiled with the desired `compile options`
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0030199..946b633 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -82,16 +82,6 @@ endif(TARGET Eigen3::Eigen)
 
 if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
   target_compile_options(${PROJECT_NAME} INTERFACE -ftemplate-depth=512)
-elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
-  # GCC is not strict enough by default, so enable most of the warnings.
-  target_compile_options(${PROJECT_NAME} INTERFACE
-    -Werror=all
-    -Werror=extra
-    -Wno-unknown-pragmas
-    -Wno-sign-compare
-    -Wno-unused-parameter
-    -Wno-missing-field-initializers
-  )
 elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
   target_compile_options(${PROJECT_NAME} INTERFACE /bigobj)
 endif()
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index 47ebf57..24bdd23 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -44,6 +44,18 @@ function(manif_add_gtest target)
   add_dependencies(${target} gtest)
   target_link_libraries(${target} ${PROJECT_NAME} gtest)
 
+  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
+    # GCC is not strict enough by default, so enable most of the warnings.
+    target_compile_options(${target} PRIVATE
+      -Werror=all
+      -Werror=extra
+      -Wno-unknown-pragmas
+      -Wno-sign-compare
+      -Wno-unused-parameter
+      -Wno-missing-field-initializers
+      )
+  endif()
+
   add_test(NAME ${target} COMMAND ${target})
 endfunction()
 ```

cc @traversaro @prashanthr05

**Comment by prashanthr05** [comment]
> I'm trying to import manif in my application, however when I tried to compile it I got the following errors due to unused-variable.

I also faced similar problems.

**Comment by GiulioRomualdi** [comment]
This commit should solve the problem https://github.com/GiulioRomualdi/manif/commit/4d24db396e6afa57b3de72b52ee1f92df6e0adba

**Comment by artivis** [comment]
Indeed those flags probably shouldn't be propagated to clients projects.
@GiulioRomualdi please feel free to open a PR with your fix. Don't forget to set the compile options for the examples too (e.g. [here](https://github.com/artivis/manif/blob/devel/examples/CMakeLists.txt#L32)).
