### ISSUE TITLE
EPS is not suitable for float32

### ISSUE THREAD

**Issue by huhumeng2** [artivis/manif#171]
https://github.com/artivis/manif/blob/b2f777967f343b51ba954fa641c9a256564f536a/include/manif/constants.h#L51

hi, guys, i found this line will throw out an error because the quaternion not normalized, but i have used the quaternion normalize function provided with eigen. i think this problem maybe 1e-15 is not suitable for float32 value, 1e-6 will be more suitable for it.

**Comment by artivis** [comment]
Hi, thanks for reporting this, I will look into it as soon as possible.
