### ISSUE TITLE
How to do point transform using SE3 and Eigen::Vector3d?

### ISSUE THREAD

**Issue by niebayes** [artivis/manif#174]
I checked the API and found that there's no overloaded operator * for SE3 and Eigen::Vector3d. How can I do point transform with one line of codes using manif?

**Comment by artivis** [comment]
Hi, the group action on a point is performed with the function `act`:
```cpp
point_transformed = X.act(point);
```
If you are using homogeneous coordinates, you can use either `transform` or `isometry`,
```cpp
point_h_transformed = X.transform() * point_h;
```

**Comment by joansola** [comment]
solved. closing.
