### ISSUE TITLE
Relationship betweeen body's linear, angular velocity between local delta rotation and delta translation

### ISSUE THREAD

**Issue by narutojxl** [artivis/manif#178]
Hi all,
Thanks for authors paper very much !
![image](https://user-images.githubusercontent.com/6205343/100498985-01863380-31a1-11eb-9186-33e8e83970b9.png)

**Comment by joansola** [comment]
This is correct. But you can do it simpler.

- build the `se(3)` tangent velocity `vel = (v,w) \in R^6`, with `v`, `w` in body frame (local frame, thus tangent to `SE(3)` manifold at the point `T` at all times)
- compute the integral during `dt`, that is, `DT = Exp(vel*dt) \in SE(3)` with `Exp` the exponential map of `SE(3)`
- Have `DT = [DR Dt ; 0 1] \in SE(3)` by definition, with `DR \in SO(3)` and `Dt \in R^3`
- Conclude the same as you have for `DR` and `Dt`.
- Also, `T_1 = T_0*DT = [R_1, t_1; 0 1]` and therefore `R_1 = R_0*Exp(w*dt)` and `t_1 = t_0+R_1*V(w*dt)*v*dt`

**Comment by narutojxl** [comment]
Thanks for author's detail reply ! Your paper is really friendly and profound, i learned a lot from your knowledge and sharing, thanks again !  BTW, it is a typo `p_1 = t_0+R_0*V(w*dt)*v*dt`. My problem is solved, close it now.

**Comment by joansola** [comment]
fixed typo
