### ISSUE TITLE
Broken exp().log() in SO3/SE3

### ISSUE THREAD

**Issue by artivis** [artivis/manif#180]
The following test is broken in `SO3/SE3`:
```cpp
delta == delta.exp().log();
```
It fails roughly as often is passes. The test that was supposed to check this was not run (my bad for not fixing a copy/paste).

Note that `SE3` relies on `SO3` for a part, so most likely the issue comes from `SO3`.
Note also that `state.log().exp()` seems to work fine and is properly tested in CI.

I added a minimal reproducible example [here on branch `fix/exp_log`](https://github.com/artivis/manif/commit/6b499719f910ee17e739b79b6914acf5501264e8#diff-80b600a72e65d107d204a378d72aeaa0206a3f47d24fa3e810d0efa1dd8de590).

**Comment by joansola** [comment]
norm(delta) must be below pi for this test to pass safely. Is this condition strictly true?

**Comment by artivis** [comment]
Oh I see. You mean "norm(delta) < pi" strictly true? Probably not. I'll have to rethink the test then

**Comment by artivis** [comment]
I can confirm that indeed it fails when `norm(delta) > pi` :+1: .
Should I remove that test altogether?

**Comment by joansola** [comment]
No, you should ensure SO3Tangent.Random() behaves as expected. Or, you should constrain the value in the test.

Beware of SE3 to conform to the same for its SO3 part.

**Comment by joansola** [comment]
At least, we should discuss whether random() should be safely bounded by -pi/pi. I think it should, but there are arguments against too

**Comment by joansola** [comment]
if we conclude random() can return whatever, then state.log().exp() == state is a sufficient test, and tangent.exp().log() should be removed as irrelevant.

**Comment by artivis** [comment]
I think it should be bounded by -pi/pi too. One can always rescale to whatever.

**Comment by joansola** [comment]
Is Eigen::Random() uniform or Gaussian?

**Comment by artivis** [comment]
> Is Eigen::Random() uniform or Gaussian?

"Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types." [from the doc](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase.html#ae814abb451b48ed872819192dc188c19).

**Comment by joansola** [comment]
Then Vector3d::Random() is uniform in the unit cube, not in the unit sphere. It's tricky to make it work properly since we want the unit sphere to be uniformly distributed. This is similar, but different, than the discussion we had long ago about Quaternion::Random().

I'd start somewhere easy... e.g. `Vector3d::Random()::normalized()*M_PI`

**Comment by joansola** [comment]
And add a comment about the way this is done, and the fact that it is somewhat arbitrary

**Comment by joansola** [comment]
Otherwise, remove the test and add a note somewhere about SO3Tg::Random() returning a number in the unit cube --- so up to the user to make a proper use

**Comment by joansola** [comment]
This is perhaps more honest from our part, but perhaps less useful

**Comment by joansola** [comment]
The test can be used if `normalized()*M_PI` is added to it --  I mean in the test body itself.

**Comment by artivis** [comment]
`normalized()*M_PI` will results in all random vectors being norm `M_PI`.
How about the following?
```cpp
vec3.setRandom();
vec3 *= (M_PI / 3);
```
Still not proper but at least the norm is in `[0.M_PI]`

**Comment by joansola** [comment]
haha yep youre right

but your code seems not right at all!  Why pi/3 ???

**Comment by joansola** [comment]
you can do

```c++
SO3Tangent t = SO3Tangent::Random()
while t.norm() > 1
t = SO3Tangent::Random()
```

**Comment by joansola** [comment]
this will return a true random in the sphere

**Comment by artivis** [comment]
> but your code seems not right at all! Why pi/3 ???

`vec3.setRandom()` norm is in `[0,3]` so I rescale the vector so that its norm is in `[0,M_PI]`.

**Comment by joansola** [comment]
why is vec3::rdm() in [0..3]??

**Comment by joansola** [comment]
it should be in [-1,1]x[-1,1]x[-1,1], the unit cube

**Comment by joansola** [comment]
`and in the [-1:1] range for floating point scalar types.`

**Comment by artivis** [comment]
> why is vec3::rdm() in [0..3]??
My bad, `vec3::rdm()` each elements are in `[-1,1]` so `vec3::rdm().norm` is in `[0,sqrt(3)]`

**Comment by joansola** [comment]
yes, but it is not a sphere, so the norm distribution is not useful here to later scale it up. You will get a cube of side 2PI but not a sphere.

**Comment by joansola** [comment]
my code with the while is a true uniform sphere. However it's not guaranteed to execute in a single go.

other option is to get the direction and discard the magnitude, convert the direction to a unit vector and build a random magnitude in [0..PI], then multiply the unit direction by this magnitude.

**Comment by joansola** [comment]
this:

https://www.google.com/search?q=C%2B%2B+get+3D+points+uniformly+distributed+inside+a+sphere&oq=C%2B%2B+get+3D+points+uniformly+distributed+inside+a+sphere&aqs=chrome..69i57.16157j0j7&sourceid=chrome&ie=UTF-8

**Comment by artivis** [comment]
> my code with the while is a true uniform sphere. However it's not guaranteed to execute in a single go.
> 
> other option is to get the direction and discard the magnitude, convert the direction to a unit vector and build a random magnitude in [0..PI], then multiply the unit direction by this magnitude.

I like this second option better.

**Comment by joansola** [comment]
https://stackoverflow.com/questions/5408276/sampling-uniformly-distributed-random-points-inside-a-spherical-volume
 

actually, from results above, some are on the surface of the sphere. This one here is INSIDE THE VOLUME, which is what we are after

**Comment by joansola** [comment]
This one is really cool:

```
There is a brilliant way to generate uniformly points on sphere in n-dimensional space, and you have pointed this in your question (I mean MATLAB code).

Why does it work? The answer is: let us look at the probability density of n-dimensional normal distribution. It is equal (up to constant)

exp(-x_1*x_1/2) *exp(-x_2*x_2/2)... = exp(-r*r/2), so it doesn't depend on the direction, only on the distance! This means, after you normalize vector, the resulting distribution's density will be constant across the sphere.

This method should be definitely preferred due to it's simplicity, generality and efficiency (and beauty). The code, which generates 1000 events on the sphere in three dimensions:

size = 1000
n = 3 # or any positive integer
x = numpy.random.normal(size=(size, n)) 
x /= numpy.linalg.norm(x, axis=1)[:, numpy.newaxis]
BTW, the good link to look at: http://www-alg.ist.hokudai.ac.jp/~jan/randsphere.pdf

As for having uniform distribution within a sphere, instead of normalizing a vector, you should multiply vercor by some f(r): f(r)*r is distributed with density proportional to r^n on [0,1], which was done in the code you posted
```

**Comment by joansola** [comment]
This is actually the one I told you (the discarding method)

```
Generate a set of points uniformly distributed within a cube, then discard the ones whose distance from the center exceeds the radius of the desired sphere.
```

**Comment by joansola** [comment]
Oh, I think this one is cool:

```
While I prefer the discarding method for spheres, for completeness I offer the exact solution.

In spherical coordinates, taking advantage of the sampling rule:

phi = random(0,2pi)
costheta = random(-1,1)
u = random(0,1)

theta = arccos( costheta )
r = R * cuberoot( u )
now you have a (r, theta, phi) group which can be transformed to (x, y, z) in the usual way

x = r * sin( theta) * cos( phi )
y = r * sin( theta) * sin( phi )
z = r * cos( theta )
```

**Comment by joansola** [comment]
All these quoted answers come from this link https://stackoverflow.com/questions/5408276/sampling-uniformly-distributed-random-points-inside-a-spherical-volume

**Comment by artivis** [comment]
> Oh, I think this one is cool:
> 
> ```
> While I prefer the discarding method for spheres, for completeness I offer the exact solution.
> 
> In spherical coordinates, taking advantage of the sampling rule:
> 
> phi = random(0,2pi)
> costheta = random(-1,1)
> u = random(0,1)
> 
> theta = arccos( costheta )
> r = R * cuberoot( u )
> now you have a (r, theta, phi) group which can be transformed to (x, y, z) in the usual way
> 
> x = r * sin( theta) * cos( phi )
> y = r * sin( theta) * sin( phi )
> z = r * cos( theta )
> ```

That's the one I'm implementing right now :+1:

**Comment by joansola** [comment]
still, phi is uniform and it should not be

**Comment by joansola** [comment]
I think a good method is this (my invention)

1. pick X from -1 to 1. 
2. given X, you have slice of the sphere at x=X. This slice is a circle of radius Ryz = 2cos(arcsin(X))
3. pick Y from -Ryz to Ryz
4. given X and Y, then Z is in the segment Sz = 2cos(arcsin(Y))
5. Pick Z from -Sz to Sz

**Comment by joansola** [comment]
I'd need to check the formulas, but im going to bed now

**Comment by joansola** [comment]
```
@Tim: As I said in the comments to Jim's answer, most books prefer the discard method for spheres. Even with hardware support cube roots take a few cycles, and the trig needed to get back to Cartesian coordinates cost some time too. Also note that I've hidden a second application of this method by drawing costheta uniformly. – dmckee --- ex-moderator kitten Mar 23 '11 at 17:06 

Ah okay I get it. The cost of running the cubed root for all of them is more than the cost of everything thrown out. I think I will do it both ways and allow me to decide on use of the function. Anyways thank you again for your help! – Tim McJilton Mar 23 '11 at 17:26 
```

So +1 for the discarding method

**Comment by joansola** [comment]
```
most books prefer the discard method for spheres
```

**Comment by joansola** [comment]
> phi = random(0,2pi)
> costheta = random(-1,1)
> u = random(0,1)
> 
> theta = arccos( costheta )
> r = R * cuberoot( u )
> now you have a (r, theta, phi) group which can be transformed to (x, y, z) in the usual way
> 
> x = r * sin( theta) * cos( phi )
> y = r * sin( theta) * sin( phi )
> z = r * cos( theta )

Seems good

![image](https://user-images.githubusercontent.com/2467261/101474019-d511aa80-394a-11eb-8e04-8c5dc3941c25.png)

**Comment by joansola** [comment]
However, consider the "discarding" implementation, maybe we gain some CPU time as pointed out by the comments I posted above.

**Comment by joansola** [comment]
> ```c++
> ```c++
> SO3Tangent t = SO3Tangent::Random();
> while t.norm() > 1
>     t = SO3Tangent::Random();
> t *= M_PI;
> ```
> 
> 
>       
> ```

Works too, and in matlab seems quite faster:

![image](https://user-images.githubusercontent.com/2467261/101477337-5ff4a400-394f-11eb-9852-a531dfda570e.png)

**Comment by joansola** [comment]
execution times:
t_discard =
   3.3566e-06
t_sampling =
   6.0331e-07

so the first method is way faster than the discard method in a naive matlab implementation.

Here both balls of radius PI , and their slices of thickness 0.1 showing uniform distributions, as desired 

![image](https://user-images.githubusercontent.com/2467261/101483933-2759c800-3959-11eb-96b7-39da8302bcef.png)
