### ISSUE TITLE
How to prove Formula 33? In the paper.

### ISSUE THREAD

**Issue by lianbin** [artivis/manif#192]
![image](https://user-images.githubusercontent.com/7082568/103050226-cecc3100-45ce-11eb-8988-bc5f7cd37285.png)

**Comment by pettni** [comment]
For any tau,
![](https://latex.codecogs.com/gif.latex?\textbf{Ad}_X&space;\textbf{Ad}_{X^{-1}}&space;\tau&space;=&space;\textbf{Ad}_X&space;\left(&space;X^{-1}&space;\hat&space;\tau&space;X&space;\right)^\vee&space;=&space;(X&space;X^{-1}&space;\hat&space;\tau&space;X&space;X^{-1})^\vee&space;=&space;\tau).

**Comment by lianbin** [comment]
> From the definition, for any tau,
> ![](https://camo.githubusercontent.com/60352ef35ed032a4fc7dec94c58407b07e54d3c34b58ae31fe776ac58ca3e110/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f25354374657874626625374241642537445f582673706163653b25354374657874626625374241642537445f253742582535452537422d312537442537442673706163653b2535437461752673706163653b3d2673706163653b25354374657874626625374241642537445f582673706163653b2535436c656674282673706163653b582535452537422d312537442673706163653b2535436861742673706163653b2535437461752673706163653b582673706163653b2535437269676874292535452535437665652673706163653b3d2673706163653b28582673706163653b582535452537422d312537442673706163653b2535436861742673706163653b2535437461752673706163653b582673706163653b582535452537422d31253744292535452535437665652673706163653b3d2673706163653b253543746175).

Oh,thank you ,my brother.  so smart you are!
