### ISSUE TITLE
why the variance is infinite？

### ISSUE THREAD

**Issue by lianbin** [artivis/manif#193]
There is a paragraph in the paper   "For example, a 3D orientation that is known up to rotations in the horizontal plane can be associated to a covariance ![image](https://user-images.githubusercontent.com/7082568/103274143-e9057500-49fb-11eb-99fe-32ea09f3837a.png)"。 Can someone explain why the variance is infinite？？

**Comment by joansola** [comment]
In the global frame, the third of these numbers corresponds to the variance of the Yaw angle. Since this angle is unknown, its variance can be set to infinity.
