### ISSUE TITLE
Add the possibility to retrieve the linear and angular part of the SE3::Tangent object

### ISSUE THREAD

**Issue by GiulioRomualdi** [artivis/manif#197]
In the `SE3` class there are some methods that allow the user to extract the rotation and translation element from an SE3 object

https://github.com/artivis/manif/blob/10e1529d03a73c41832be8b811a68ef58848dde4/include/manif/impl/se3/SE3_base.h#L127-L140

These kinds of methods are missing in SE3::Tangent. 

If you are interested in having this feature I can propose a PR

**Comment by artivis** [comment]
The class `SE3Tangent` has the getters [`BlockV v()`](https://github.com/artivis/manif/blob/10e1529d03a73c41832be8b811a68ef58848dde4/include/manif/impl/se3/SE3Tangent_base.h#L108) and [`BlockW w()`](https://github.com/artivis/manif/blob/10e1529d03a73c41832be8b811a68ef58848dde4/include/manif/impl/se3/SE3Tangent_base.h#L112) - soon to become `linVel` and `angVel` in https://github.com/artivis/manif/pull/190. 
Isn't that what you are looking for?

**Comment by GiulioRomualdi** [comment]
> Isn't that what you are looking for?

It's actually what I was looking for! Thank you very much!
