### ISSUE TITLE
No skew function available for custom scalar types

### ISSUE THREAD

**Issue by pettni** [artivis/manif#198]
Custom scalar types don't necessarily specialize ```std::is_arithmetic``` (doing so in isolation seems to cause a host of other problems in some cases). This causes a problem with the SFINAE ```skew``` functions.

Example:
```
#include <manif/impl/traits.h>
#include <manif/impl/eigen.h>

// example "autodiff" type
struct MyDouble
{
  MyDouble(double d)
    : d_(d)
  {}

  double d_;
};

int main()
{
  Eigen::Matrix<double, 6, 1> v = Eigen::Matrix<double, 6, 1>::Zero();

  // these should call the scalar version
  manif::skew(1.0);
  manif::skew(MyDouble(1));

  // these should call the vector version
  manif::skew(Eigen::Vector3d{1, 2, 3});
  manif::skew(v.head<3>());
}
```

**Comment by artivis** [comment]
For reference, a possible solution is drafted in [this comment](https://github.com/artivis/manif/pull/194#discussion_r551940788).
