### ISSUE TITLE
Can it support c++14?

### ISSUE THREAD

**Issue by shanpenghui** [artivis/manif#205]
I use c++14 to run slam used eigen, g2o and pcl on ubuntu20, but i still can not find a library support c++14, can this lib do that?
Sry for that if disturb because i know this lib very little. I'm very appreciate if somebody can help. Tks very much.

**Comment by artivis** [comment]
`manif` is written in c++11, it can thus be used with c++14. Please refer to the [online documentation](https://artivis.github.io/manif/cpp/index.html) to see how to use it with your own project.
