### ISSUE TITLE
Jacobian Block In Left Plus

### ISSUE THREAD

**Issue by yangzhen1031** [artivis/manif#208]
In Left Plus, 
![image](https://user-images.githubusercontent.com/58388189/110965580-49674a00-838f-11eb-8004-7cb16982b4a0.jpeg)

Tangent space is expressed in the global frame, why in code (Lie_group_base.h)

J_mout_t = inverse().adj()*rjac();

not 

J_mout_t = inverse().adj()*ljac();

?

**Comment by artivis** [comment]
Hi,

in manif, all Jacobians are differentiated with respect to a local perturbation on the tangent space, as stated in [the documentation](https://artivis.github.io/manif/#autotoc_md7). We do that for consistency purpose.

There is no plan right now to implement Jacobians wrt a global perturbation altho it is discussed in #116.

This being said, keep in mind that the adjoint matrix (`x.adj()`) linearly transforms vectors of the local tangent space at onto vectors of the global tangent space. This allows you to e.g. map a covariance matrix from the global space to the local one, performs the uncertainty propagation with the Jacobians provided in manif and then map the covariance matrix back from local to global.
