### ISSUE TITLE
Add the possibility to install the python bindings

### ISSUE THREAD

**Issue by GiulioRomualdi** [artivis/manif#209]
Hi @artivis! First of all, thank you very much for developing the python bindings. They are really useful.

As far as I understood, there seems that the bindings are not currently installed. I can easily propose a minimum change in the CMake file to install the bindings.

**Comment by artivis** [comment]
Hi @GiulioRomualdi,
Glad to see that the Python binding is useful.

As of now, the Python binding is meant to be installed through `pip`; from the [online doc](https://artivis.github.io/manif/python/index.html): 
```bash
cd manif
python3 -m pip install .
```
Actually, the `setup.py` file invokes the `CMakeLists.txt`. Thus I'm afraid your PR #211 will introduce issues in its current state.

**Comment by GiulioRomualdi** [comment]
Hi @artivis I've just installed `manifpy` from pip and everything went fine. Thank you! 
I think we can close the issue
