### ISSUE TITLE
Lie group way for visual-inertial sensor fusion

### ISSUE THREAD

**Issue by tenneck** [artivis/manif#220]
Good evening,

I've been working with quaternions for quite a while now and also have been using those for visual-inertial sensor fusion. More specifically, I used an quaternion EKF with error-state representation.

This project has caught my attention a couple weeks ago and I was trying to get the ideas of Lie groups and algebra. Although I was initially focusing on just getting an understand of Lie groups, I now think it has the potential of changing quite a lot in the field of state estimation.

The question I'm going to ask is very specific: After looking at the examples you provided, I'm still unsure whether the SE(3) or SE_2(3) is the preferred way to go for IMU-vision sensor fusion. The SE_2(3) seems to be a small modification of the SE(3).

It would be great if you could give me a hint of which of the provided examples I should be using as a starting point. Also, if you know any papers regarding this question, this would be helpful as well.

Thank you in advance.

Regards,
- T

**Comment by artivis** [comment]
Hi,

If you are rocking an IMU you'll probably want to use SE_2(3) for your visual-inertial algorithm. But really that's up to you and how you formalize your problem.

As for references, I'll assume you had a look at [our paper accompanying this library](https://arxiv.org/pdf/1812.01537.pdf) for an introduction to Lie theory. As for the SE_2(3)-based visual-inertial bit, the paper ["Invariant Kalman Filtering for Visual Inertial SLAM" M. brossard & al.](https://hal.archives-ouvertes.fr/hal-01588669/document) is probably a good starting point in your research.

Best.

**Comment by tenneck** [comment]
Hi Jeremie,

thanks for the very fast reply. I did have a look at your paper, which is very helpful as a starting point. I'll have a look at the other paper you mentioned.

Once I get to free up some of my time I'll start implementing a SE_2(3) based visual-inertial algorithm. I might come back with either questions or contributions.

Best,
T
