### ISSUE TITLE
ljacinv

### ISSUE THREAD

**Issue by lianbin** [artivis/manif#223]
https://github.com/artivis/manif/blob/devel/include/manif/impl/so3/SO3Tangent_base.h#L214
accroding to:
![image](https://user-images.githubusercontent.com/7082568/115362150-d3f36280-a1f3-11eb-8ffc-b32160b55815.png)

  if (theta_sq <= Constants<Scalar>::eps_s)
    return Jacobian::Identity() + Scalar(0.5) * W; 

Should be changed to

  if (theta_sq <= Constants<Scalar>::eps_s)
    return Jacobian::Identity() -  Scalar(0.5) * W; 
 
Is that right?

**Comment by joansola** [comment]
Yes it seems so! Thanks for pointing this out!
