### ISSUE TITLE
Any plan for tag 0.0.4 ?

### ISSUE THREAD

**Issue by traversaro** [artivis/manif#230]
Hi @artivis, 
    first of all, sorry for bothering you and thanks as usual for the library. : ) 

Do you have any plan of doing a tag out of the current master branch, for example creating a 0.0.4 tag? For several reasons, for us (i.e. https://github.com/dic-iit) it would be quite convenient to have a tag after https://github.com/artivis/manif/pull/190, so that we can easily target from the same code base both a "tagged" version and the latest master. As usual, nothing specific about support is to be intended out of this tag, it it just more convenient to refer to 0.0.4 rather then using a checkout or referring  to "manif master branch of late May 2021". : )

If there is anything we can do to help the tag process, please let us know. If instead you don't have time or you prefer for any reason not to do a tag now, no problem! 

Thanks in advance, 
           Silvio

**Comment by artivis** [comment]
Hi,
you're not bothering at all. I'm always happy to see this lib being used :+1:.

I was actually hopping to get #207 through before releasing a new tag but I could also tag now. I'll look at it asap.

**Comment by traversaro** [comment]
Thanks! For what regards https://github.com/artivis/manif/pull/207 I do not know what @GiulioRomualdi is thinking about, given that I don't think a new release of tl-optional is happening soon (see https://github.com/TartanLlama/optional/issues/46), probably we could just import the latest one from the master branch, as this should solve the CI failure.

**Comment by artivis** [comment]
Indeed refreshing the TartanLlama/optional src file together with addressing the couple suggestion I made would do.
But this isn't blocking in any ways; I'll tag manif some time this week.

**Comment by GiulioRomualdi** [comment]
#207 should be ready 😃

**Comment by artivis** [comment]
Tag [0.0.4](https://github.com/artivis/manif/releases/tag/0.0.4) is out!

**Comment by traversaro** [comment]
Thanks a lot @artivis !
