### ISSUE TITLE
Small angle approximation for SO3 right and left Jacobians

### ISSUE THREAD

**Issue by xianlopez** [artivis/manif#247]
Hi. First of all thanks for the great paper and this C++ library.

I was trying to implement the right Jacobian of SO3 myself and realized that equation 143 is not well defined for theta = (0, 0, 0). Looking at the implementation in this library I see that you do an approximation when the vector is small. However, that's not mentioned in the paper (or I couldn't find it). Could you please explain how you arrive to that result? Looking at equations 143 to 146, it's not clear to me how you solve the indeterminate and get to that approximation.

**Comment by joansola** [comment]
To find small-angle approximations, substitute sin(theta) and cos(theta) by their Taylor expansions, cancel the terms with those in the denominator, and truncate the remaining terms at the desired length.

For example t e following term appearing in the right Jacobian:
```
(1 - cos (a) ) / a^2 ~ (1 - (1 - 0.5 a^2 + 1/24 a^4)) / a^2 = (0.5a^2 - 1/24a^4) / a^2 = 0.5 -1/24 * a^2 ~ 0.5
```

You proceed akin with the other term `(a - sin(a) ) / a^3`

**Comment by xianlopez** [comment]
Aha, that makes sense, thanks for the quick answer!

The term `(a - sin(a)) / a^3` gives me `1/6`, but I guess that's ignored because it multiplies a quadratic term, `[theta]_x^2`, right?

**Comment by joansola** [comment]
Yes, you would get (I might have put the signs wrong)
```
Jl(a) = I + [a]x / 2 + [a]x^2 / 6 + ...
```
and you may decide to truncate before the quadratic term -- this is up to you.
