### ISSUE TITLE
Global versus local tangent space

### ISSUE THREAD

**Issue by stefangachter** [artivis/manif#270]
I am unsure if this is the right place to ask this question. I studied the paper related to manif and the questions raised here but consulted other works as well. I am very thankful for all the contributions! It helped me a lot to understand the theory. -- As a practitioner, I am somewhat confused about the choice of the "global" or "local" frame to express perturbation. As far as I understand, it is possible to transform from "global" to "local" or back. If I am not mistaken, "manif" uses consistently "local" perturbation (ie., "right" plus and minus operators and "right" Jacobians). I understand that certain errors are given "naturally" in a "global" or "local" frame (e.g., section H in the paper on rotations in the horizontal plane). However, I am wondering if there are theoretical arguments (e.g. better estimation consistency) to choose either "global" or "local". Is there a paper discussing the choice between the two perturbations?

**Comment by joansola** [comment]
Hi Stephan, thanks for writing.

You should look at the literature around "invariant Kalman filter" and similar, by Barrau and Bonnabel, to get the theoretical insights you are looking for. Global errors seem to behave better than local errors in terms of consistency. Barrau and Bonnabel works explain why and how. It-s a little theoretical but very much related to Lie theory so it should be doable.

**Comment by stefangachter** [comment]
Thanks, Joan, for your fast reply! -- Indeed, I already started to study the work on "invariant" filtering. I appreciate the work and understand the practical implications. I was wondering if this work can be "generalized" but probably not. It is up to me to analyze each use case. --- In particular, I am wondering what to do in case of "mixed" measurements, e.g. "absolute position measurements" from GNSS sensor and "relative pose measurements" from a camera. Again, it is probably up to me to do the math.
