### ISSUE TITLE
Minus operator of SE(3) in paper

### ISSUE THREAD

**Issue by stefangachter** [artivis/manif#279]
I am writing some unit tests based on formulas stated in the "Micro Lie Theory" paper: https://arxiv.org/pdf/1812.01537.pdf
I have a question regarding example 7 on page 11.
The minus operator of SE(3) is given by:
![image](https://github.com/artivis/manif/assets/7974580/c2847692-1f9b-4ea5-a1f5-cf7e79d2035f)
I am not sure how to read V1. First, I thought that it should be V1 derived of R1. But doing the computation, hopefully correctly, I conclude that it should be:
![image](https://github.com/artivis/manif/assets/7974580/989c7f81-6911-42f9-9654-c0dcb3406aeb)
Thus, V is computed based on Log(R1^T*R2) and not on R1.
Is my understanding correct?

**Comment by joansola** [comment]
Yes, it is `V(theta)`, with `theta = R2 (-) R1 = Log(R1.T * R2)`
