### ISSUE TITLE
Build tests for Mac are obsolete

### ISSUE THREAD

**Issue by joansola** [artivis/manif#290]
macOS is already at version 14. Tests of manif currently are for versions 11 and 12.

- Last version is 14
- Maintained versions are 12 and 13
- Version 11 is no longer maintained by Apple.

**Comment by artivis** [comment]
GitHub [runners supports 11 to 13, 14 is in beta](https://docs.github.com/fr/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).  
We could add at least 13 :+1: .
