### ISSUE TITLE
ceres/autodiff_local_parameterization.h removed in Ceres 2.2.0

### ISSUE THREAD

**Issue by axbycc-mark** [artivis/manif#296]
The file ceres/autodiff_local_parameterization.h was removed by the Ceres project in commit 68c53bb39552cd4abfd6381df08638285f7386b3

This file is imported currently here.
https://github.com/artivis/manif/blob/03c497df3364e999cec46fe4f974eae1959a34e1/include/manif/ceres/ceres_utils.h#L8

A related comment from the removed file used to read
```
// WARNING: LocalParameterizations are deprecated, so is
// AutoDiffLocalParameterization. They will be removed from Ceres Solver in
// version 2.2.0. Please use Manifolds and AutoDiffManifold instead.
```

I'm currently looking into how to migrate to AutoDiffManifold

**Comment by artivis** [comment]
Hi @axbycc-mark,
Thanks for opening this issue. The migration is actually already tackled in #295 . It still requires a little tho.
