### ISSUE TITLE
CMakeLists sets ${PROJECT_VERSION} to 0.0.3 (outdated)

### ISSUE THREAD

**Issue by fglinka** [artivis/manif#312]
Hi,

while installing manif into a ROS2 workspace, I noticed that the generated `manifConfigVersion.cmake` still set the PACKAGE_VERSION to 0.0.3 even though I used the most recent commit from `devel`. The version wasn't bumped [in the CMakeLists.txt](https://github.com/artivis/manif/blame/devel/CMakeLists.txt#L4). It would be helpful to bump it again because I use it to check that I have compatible versions of manif (>= 0.0.5) and Ceres (>=2.2.0) to use the new manifold api for autodiff. I didn't create a pull request because I was not sure whether you want to have version 0.0.5 or 0.0.6 on the devel branch.

**Comment by artivis** [comment]
Releases happens on the `master` branch were the [CMakeLists](https://github.com/artivis/manif/blob/c49fec8150e62821d9be7e2a3ac49db75bf7bb92/CMakeLists.txt#L4) and [package.xml](https://github.com/artivis/manif/blob/c49fec8150e62821d9be7e2a3ac49db75bf7bb92/package.xml#L4) are up-to-date. This is indicated in the [CONTRIBUTING guidelines](https://github.com/artivis/manif/blob/devel/CONTRIBUTING.md).
I know this branching model isn't quite ideal and I do plan on changing it in the future. In the meantime you can simply checkout the `master` branch.

**Comment by fglinka** [comment]
Oh okay, that fixes it thank you. Terribly sorry I have read the guidelines but not checked the master branch because `devel` was the default branch.

BTW: Thank you guys for the library and the great Lie theory paper. It was a real help during my Master's.

**Comment by artivis** [comment]
Eheh no problem don't worry. And thanks for the kind words!
