### ISSUE TITLE
Questions for se2_localization example

### ISSUE THREAD

**Issue by Chris7462** [artivis/manif#313]
https://github.com/artivis/manif/blob/de52f8b8bf354e5e03a61025986f4fdb1abad774/examples/se2_localization.cpp#L237

I think the left-plus should be used in the propagation step as the measurement model is of the form $y\_k = h(\chi, b\_k) = \chi^{-1} * b\_k$ and is thus right-invariant.

https://github.com/artivis/manif/blob/de52f8b8bf354e5e03a61025986f4fdb1abad774/examples/se2_localization.cpp#L257
Also, innovation should be rewrite so that the right-invariant error appears,
```math
\begin{align}
\mathbf{z} & = \check{\chi}(\mathbf{y}-\check{\mathbf{y}})\\
& = \check{\chi}(\chi^{-1}\mathbf{b}+\mathbf{v}-\check{\chi}\mathbf{b})\\
\end{align}
```

https://github.com/artivis/manif/blob/de52f8b8bf354e5e03a61025986f4fdb1abad774/examples/se2_localization.cpp#L267
This should be left-plus as well.

**Comment by joansola** [comment]
In right plus, the vector is defined locally to the group element. In left plus, the vector is defined in the global reference.

In this example, since the control action of the robot is local (advance forward, turn left) and not global (move North), the operation to use is right-plus.

Once you have chosen right plus, you syrtem will be left-invariant. You have no choice here. You can not choose left-right invariance with local-global action independently. You have only one option (the system is exactly as it is, and in our case our control vector `u` is defined locally) and then you can deduce the type of invariance (left or right) as a consequence. So in fact you have no choice.

**Comment by Chris7462** [comment]
Okay, the propagation model is left-invariant (right-plus), while the measurement model is right-invariant (left-plus). Shouldn't the covariance change from left-invariant to right-invariant in this example?

In addition, the innovation calculation is different from the other pull request we discussed earlier. Rewriting it to reflect the right-invariant error seems more logical to me.

The reason I thought the left-plus operation should be used is that if we start from the right-invariant definition with the robot's control action in the local frame, i.e., $\chi_{t}=\chi_{t-1}\text{Exp}(u_t+\epsilon_{t})$, where $\epsilon_{t}$ is the noise:
```math
\begin{align}
  \eta_{t}^{R} & =\chi_{t}\hat{\chi}_{t}^{-1}\\
  & = \chi_{t-1}\text{Exp}(u_{t})\text{Exp}(\epsilon_{t})\hat{\chi}_{t}^{-1}\\
  & = \chi_{t-1}\text{Exp}(u_{t})\hat{\chi}_{t}^{-1}\hat{\chi}_{t}\text{Exp}(\epsilon_{t})\hat{\chi}_{t}^{-1}\\
  & = \chi_{t-1}\text{Exp}(u_{t})\text{Exp}(u_{t})^{-1}\hat{\chi}_{t-1}^{-1}\hat{\chi}_{t}\text{Exp}(\epsilon_{t})\hat{\chi}_{t}^{-1}\\
  & = \eta_{t-1}^{R}\text{Exp}(\text{Ad}_{\hat{\chi}_{t}}\epsilon_{t})\\
  \Rightarrow \text{Exp}(\xi_{t}^{R}) &
  = \text{Exp}(\xi_{t-1}^{R})\text{Exp}(\text{Ad}_{\hat{\chi}_{t}}\epsilon_{t})\\
  \Rightarrow \xi_{t}^{R} & = \xi_{t-1}^{R} + \text{Ad}_{\hat{\chi}_{t}}\epsilon_{t}
\end{align}
```
Here, the Jacobians are $F\_{t}=I$ and $W\_{t}=\text{Ad}\_{\hat{\chi}_{t}}$.

If we apply the left-plus operation at line 237, as in: `X = X.lplus(u_est, J_x, J_u);`

then $F_{t} =$ `J_x`, which is correct.

Shouldn’t $W_{t}=$`J_u` in this case?

**Comment by Chris7462** [comment]
When reviewing the implementation details of `lplus`, another question arises:
https://github.com/artivis/manif/blob/de52f8b8bf354e5e03a61025986f4fdb1abad774/include/manif/impl/lie_group_base.h#L477
According to Eq. (75) in the manif paper
```math
\textbf{J}_{l}(\tau) = \textbf{Ad}_{\text{Exp}(\tau)}\textbf{J}_{r}(\tau)
```
Why is there an inverse present here?

**Comment by artivis** [comment]
This is not Eq.(75).  
With $\tau\oplus\chi$ note that:

```math
\textbf{Ad}_{\text{Exp}(\tau)} != \textbf{Ad}_{\chi}
```

Instead, this is the chain rule:

```math
\textbf{J}^{\tau\oplus\chi}_{\tau} = \textbf{J}^{\textbf{Exp}(\tau)\cdot\chi}_{\tau} = \textbf{J}^{\textbf{Exp}(\tau)\cdot\chi}_{{Exp}(\tau)}\cdot\textbf{J}^{\textbf{Exp}(\tau)}_\tau = \textbf{Ad}_{\chi^{-1}}\cdot\textbf{J}_{r}(\tau) 
```

~~Edit: In the early days of `manif`, `ljac` was often implemented wrt `rjac`. So this was a small optimisation. It may not be as true nowadays.~~

**Comment by joansola** [comment]
@artivis you are right, but the chain rule is not `J_l(tau)`, it is `J^{tau (+) X}_tau`.

**Comment by artivis** [comment]
> @artivis you are right, but the chain rule is not `J_l(tau)`, it is `J^{tau (+) X}_tau`.

Edited :+1:

**Comment by Chris7462** [comment]
Thank you @artivis! I think I understand the difference now.

For the `lplus`, the Jacobian being computed corresponds to the model $\chi_{t}=u_{t}\oplus \chi_{t-1}$. In this context, the Jacobian $W_{t}$ is derived as:
```math
W_{t} = \textbf{Ad}_{\bar{\chi}_{t}^{-1}}J_{r}(\epsilon_{t})
```
In my previous comment, I calculated $W_{t}$ based on the right-invariant definition, where the Jacobian is derived for the model $\chi_{t}=\chi_{t-1}\oplus u_{t}$. This results in:
```math
W_{t}=\textbf{Ad}_{\bar{\chi}_{t}}J_{r}(\epsilon_{t})
```
I have noticed, this actually changes the error from the left to the right. Therefore, I cannot use `lplus` for the motion model in this case.

So shouldn't $W_t~=$  `J_u` in this case? The answer is no.
