### ISSUE TITLE
Elaborate a bit on 'a note on jacobians'

### ISSUE THREAD

**Issue by versatran01** [artivis/manif#62]
Thanks for this work.

Could you add a bit more explanation to 'a note on jacobians' section in the readme? 
For example, how should one use manif with ceres correctly.

**Comment by artivis** [comment]
Thanks for your interest in this work.

The short story is that you cannot use the analytical Jacobians that `manif` provides with `Ceres` (see e.g. [issue 387](https://github.com/ceres-solver/ceres-solver/issues/387)). I will update the readme with some more information about it.

However you can use the autodiff feature of `Ceres`. This package provides some helper classes (e.g. [`CeresLocalParameterizationFunctor`](https://github.com/artivis/manif/blob/devel/include/manif/ceres/local_parametrization.h#L9)) and functions (e.g. [make_local_parameterization_autodiff](https://github.com/artivis/manif/blob/devel/include/manif/ceres/ceres_utils.h#L17)) to ease interfacing with `Ceres`.  
You can find a short example in the [wiki](https://github.com/artivis/manif/wiki/On-the-use-with-Ceres) and some more in the [unit-tests](https://github.com/artivis/manif/blob/devel/test/ceres/gtest_se2_autodiff.cpp).

**Comment by artivis** [comment]
Closing this issue as the documentation improved since it was opened.
Feel free to re-open if the [wiki page](https://github.com/artivis/manif/wiki/Using-manif-with-Ceres) isn't enough.

**Comment by joansola** [comment]
I improved this in #129
