### ISSUE TITLE
FindEigen3 dose not find eigen

### ISSUE THREAD

**Issue by versatran01** [artivis/manif#76]
After removing it cmake correctly finds eigen (installed in /usr/local/include)

**Comment by artivis** [comment]
Hi, do you know if this issue recent ??  
Can you please provide some more info about your setup ?

**Comment by versatran01** [comment]
I have eigen 3.3.7, ubuntu 18.04.
I think eigen now exports all the cmake stuff correctly so there's no need to provide a custom findeigen.cmake.

**Comment by artivis** [comment]
Ok thanks, I will investigate :+1:
