### ISSUE TITLE
Question about Jacobian in example se2_sam/se3_sam.cpp

### ISSUE THREAD

**Issue by extr15** [artivis/manif#78]
Hi, thanks for your work!
In your example `se2_sam.cpp`(or `se3_sam.cpp`), for the prior measurement, the residual is:
`r=poses[0].log()`, so I think the jacobian is:
let `t = Log(poses[0])`, 
$ J = \partial Log(poses[0]) / \partial poses[0] = J_r^{-1}(t) $
so this line:
        `J.block<DoF, DoF>(row, col) =  MatrixT::Identity();`
should be:
`J.block<DoF, DoF>(row, col) = poses[0].log().rjacinv();`.
How do you think?

**Comment by joansola** [comment]
Hello extr15 -- whatever your name is!

Yes you are right. What happens is that this factor is so trivial that it works anyway. But indeed one should be using the derivative of `log()` which is `Jr^{-1}`. I will double check it and change it if necessary when I have a minute.

As a side note, your suggested code however could make use of the Jacobian facility of manif, by doing
```
poses[0].log().rjacinv(Jac);
J.block<DoF, DoF>(row, col) = Jac;
```

Joan

**Comment by joansola** [comment]
Hello. I had a look at this. In principle, you need Jr as indicated above. However, this Jacobian is the Identity at the point of evaluation, which is the origin, so the math in the code is perfectly fine.

I am evaluating if the example code should be made clearer. I possibly update the comments on this section first.

Thanks again

**Comment by joansola** [comment]
Fixed. Waiting for PR acceptance.

**Comment by extr15** [comment]
Thanks for your reply and work!
