### ISSUE TITLE
Installation on OSX documentation

### ISSUE THREAD

**Issue by artivis** [artivis/manif#87]

**Comment by joansola** [comment]
I do not remember any particular difference in installing manif on OSX. The following should work:

```bash
git clone [manif git URL]
cd manif
mkdir build
cd build
cmake -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON ..
make
[sudo make install]
```

I just tried and it all works (well, I did not install). The example executables execute normally. All ctests pass.

**Comment by artivis** [comment]
The only difference is probably in installing Eigen, something like `brew install eigen`.

**Comment by joansola** [comment]
Oh. But then... OK. I think it's like this then:
```
brew install eigen
```

**Comment by joansola** [comment]
Like here https://brewinstall.org/install-eigen-on-mac-with-brew/
