### ISSUE TITLE
JOSS paper - suggestions

### ISSUE THREAD

**Issue by alex-konovalov** [artivis/manif#90]
I am reviewing https://github.com/openjournals/joss-reviews/issues/1371 - couple of suggestions regarding the paper:

- "The library is mathematically grounded in (Solà, Deray, & Atchuthan, 2018)" - perhaps better to write "Mathematical foundations of the library are given in" (or "Mathematical background ..." etc).

- please fix references to Books and wave_geometry - they are not rendered correctly.

**Comment by alex-konovalov** [comment]
Also, please check what should be linked to the "Archive" link on the left of page 1. It seems that it does not work.

**Comment by alex-konovalov** [comment]
Next, I can not find version number so I can not tick "Version: Does the release version given match the GitHub release (branch: joss)?". The bibliograophy cites manif without version, and there are now releases at https://github.com/artivis/manif/releases. I suggest to publish an official release on GitHub with a proper version (see e.g. https://help.github.com/en/articles/creating-releases) and cite that one.

**Comment by artivis** [comment]
Hi @alex-konovalov,
thanks for the review. We will address it as soon as possible.

**Comment by artivis** [comment]
@alex-konovalov, we addressed your remarks as follows,
- `wave_geometry` references the library associated paper together with the github repository
- `boost` reference rendering was fixed
- The `Achive` link is part of the joss paper template, I do not think we have control over this. I believe it will be linked to a valid url once the paper published.
- `manif` will be released soon after a couple small fixes are made (pull requests opened and pending)

**Comment by alex-konovalov** [comment]
Thanks @artivis and @joansola !
